/**
 * Family 子包行为测试。
 * 输入：packages 下各子包的 src/index.ts 模块。
 * 输出：验证各 family 包只注册自己的模型，全家桶包注册全部模型。
 */

import { existsSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import { describe, expect, it } from "vitest"

/** 当前测试文件所在目录。 */
const CURRENT_DIR = dirname(fileURLToPath(import.meta.url))

/** 仓库根目录。 */
const REPO_ROOT = resolve(CURRENT_DIR, "..")

/** 各厂商包当前应覆盖的 family 与模型别名。 */
const VENDOR_PACKAGE_CASES = [
  {
    relativePath: "packages/minimax/src/index.ts",
    expectedFamilies: ["minimax-m1", "minimax-m2", "minimax-text-01"],
    expectedModels: [
      "MiniMaxAI/MiniMax-M2",
      "MiniMaxAI/MiniMax-M2.1",
      "MiniMaxAI/MiniMax-M2.5",
      "MiniMaxAI/MiniMax-M1-40k",
      "MiniMaxAI/MiniMax-M1-80k",
      "MiniMaxAI/MiniMax-M1-40k-hf",
      "MiniMaxAI/MiniMax-M1-80k-hf",
      "MiniMaxAI/MiniMax-Text-01",
      "MiniMaxAI/MiniMax-Text-01-hf",
    ],
  },
  {
    relativePath: "packages/moonshotai/src/index.ts",
    expectedFamilies: ["kimi-k2", "kimi-k2-thinking", "moonlight", "kimi-dev"],
    expectedModels: [
      "moonshotai/Kimi-K2-Base",
      "moonshotai/Kimi-K2-Instruct",
      "moonshotai/Kimi-K2-Instruct-0905",
      "moonshotai/Kimi-K2-Thinking",
      "moonshotai/Moonlight-16B-A3B",
      "moonshotai/Moonlight-16B-A3B-Instruct",
      "moonshotai/Kimi-Linear-48B-A3B-Base",
      "moonshotai/Kimi-Linear-48B-A3B-Instruct",
      "moonshotai/Kimi-Dev-72B",
    ],
  },
  {
    relativePath: "packages/dream-org/src/index.ts",
    expectedFamilies: ["dream-v0", "dreamon-v0"],
    expectedModels: [
      "Dream-org/Dream-v0-Base-7B",
      "Dream-org/Dream-v0-Instruct-7B",
      "Dream-org/Dream-Coder-v0-Base-7B",
      "Dream-org/Dream-Coder-v0-Instruct-7B",
      "Dream-org/DreamOn-v0-7B",
    ],
  },
  {
    relativePath: "packages/utter-project/src/index.ts",
    expectedFamilies: [
      "eurollm-1.7b",
      "eurollm-1.7b-instruct",
      "eurollm-2512",
      "eurollm-2512-instruct",
    ],
    expectedModels: [
      "utter-project/EuroLLM-1.7B",
      "utter-project/EuroLLM-1.7B-Instruct",
      "utter-project/EuroLLM-9B-2512",
      "utter-project/EuroLLM-9B-Instruct-2512",
      "utter-project/EuroLLM-22B-2512",
      "utter-project/EuroLLM-22B-Instruct-2512",
      "utter-project/EuroMoE-2.6B-A0.6B-2512",
      "utter-project/EuroMoE-2.6B-A0.6B-Instruct-2512",
    ],
  },
  {
    relativePath: "packages/mosaicml/src/index.ts",
    expectedFamilies: ["pythia"],
    expectedModels: [
      "EleutherAI/gpt-neox-20b",
      "mosaicml/mpt-7b",
      "mosaicml/mpt-7b-8k",
      "mosaicml/mpt-7b-storywriter",
      "mosaicml/mpt-30b",
    ],
  },
  {
    relativePath: "packages/ai21labs/src/index.ts",
    expectedFamilies: ["jamba-v0.1", "jamba2"],
    expectedModels: [
      "ai21labs/AI21-Jamba2-Mini",
      "ai21labs/AI21-Jamba2-3B",
      "ai21labs/AI21-Jamba-Reasoning-3B",
      "ai21labs/Jamba-v0.1",
    ],
  },
  {
    relativePath: "packages/stabilityai/src/index.ts",
    expectedFamilies: ["granite-code-base", "mamba-790m", "mistral-7b-v0.1"],
    expectedModels: [
      "ibm-granite/granite-3b-code-base-2k",
      "state-spaces/mamba-790m-hf",
      "mistralai/Mistral-7B-v0.1",
      "stabilityai/japanese-stablelm-3b-4e1t-base",
      "stabilityai/japanese-stablelm-3b-4e1t-instruct",
      "stabilityai/japanese-stablelm-base-gamma-7b",
      "stabilityai/japanese-stablelm-instruct-gamma-7b",
      "stabilityai/stablecode-completion-alpha-3b",
      "stabilityai/stablecode-completion-alpha-3b-4k",
    ],
  },
  {
    relativePath: "packages/sarvamai/src/index.ts",
    expectedFamilies: ["sarvam-30b", "sarvam-m"],
    expectedModels: [
      "sarvamai/sarvam-30b",
      "sarvamai/sarvam-105b",
      "sarvamai/sarvam-m",
    ],
  },
  {
    relativePath: "packages/llm360/src/index.ts",
    expectedFamilies: [
      "crystal",
      "k2",
      "k2-chat",
      "k2-think-v2",
      "mimo-7b-rl-0530",
      "snowflake-arctic-base",
    ],
    expectedModels: [
      "Snowflake/snowflake-arctic-base",
      "XiaomiMiMo/MiMo-7B-RL-0530",
      "LLM360/Amber",
      "LLM360/AmberChat",
      "LLM360/Crystal",
      "LLM360/CrystalChat",
      "LLM360/K2",
      "LLM360/K2-Chat",
      "LLM360/K2-Think",
      "LLM360/K2-Think-V2",
    ],
  },
  {
    relativePath: "packages/primeintellect/src/index.ts",
    expectedFamilies: ["bitnet-b1.58-2b-4t"],
    expectedModels: [
      "microsoft/bitnet-b1.58-2B-4T",
      "PrimeIntellect/INTELLECT-1",
      "PrimeIntellect/INTELLECT-1-Instruct",
    ],
  },
  {
    relativePath: "packages/lightonai/src/index.ts",
    expectedFamilies: ["falcon-7b", "pagnol", "pagnol-xl", "alfred-40b-1023"],
    expectedModels: [
      "tiiuae/falcon-7b",
      "lightonai/alfred-40b-0723",
      "lightonai/alfred-40b-1023",
      "lightonai/pagnol-small",
      "lightonai/pagnol-medium",
      "lightonai/pagnol-large",
      "lightonai/pagnol-xl",
    ],
  },
  {
    relativePath: "packages/deci/src/index.ts",
    expectedFamilies: ["decicoder-1b", "mistral-7b-v0.1"],
    expectedModels: [
      "mistralai/Mistral-7B-v0.1",
      "Deci/DeciCoder-1b",
      "Deci/DeciLM-7B",
      "Deci/DeciLM-7B-instruct",
    ],
  },
  {
    relativePath: "packages/bsc-lt/src/index.ts",
    expectedFamilies: ["salamandra", "salamandra-instruct"],
    expectedModels: [
      "BSC-LT/salamandra-2b",
      "BSC-LT/salamandra-2b-instruct",
      "BSC-LT/salamandra-7b",
      "BSC-LT/salamandra-7b-instruct",
      "BSC-LT/ALIA-40b",
      "BSC-LT/ALIA-40b-instruct-2601",
    ],
  },
  {
    relativePath: "packages/aidc-ai/src/index.ts",
    expectedFamilies: ["marco-o1", "qwen2", "qwen2.5"],
    expectedModels: [
      "Qwen/Qwen2-7B-Instruct",
      "Qwen/Qwen2.5-32B-Instruct",
      "AIDC-AI/Marco-Nano-Instruct",
      "AIDC-AI/Marco-Mini-Global-Base",
      "AIDC-AI/Marco-Mini-Base",
      "AIDC-AI/Marco-Nano-Base",
      "AIDC-AI/Marco-LLM-SEA",
      "AIDC-AI/Marco-LLM-AR-V4",
      "AIDC-AI/Marco-LLM-AR-V2",
      "AIDC-AI/Marco-LLM-ES",
      "AIDC-AI/Marco-o1",
    ],
  },
  {
    relativePath: "packages/datajuicer/src/index.ts",
    expectedFamilies: ["dj-refine-1b"],
    expectedModels: [
      "datajuicer/LLaMA-1B-dj-refine-50B",
      "datajuicer/LLaMA-1B-dj-refine-100B",
      "datajuicer/LLaMA-1B-dj-refine-150B",
      "datajuicer/LLaMA-1B-dj-refine-150B-instruct-4.7B",
    ],
  },
  {
    relativePath: "packages/baidu/src/index.ts",
    expectedFamilies: ["ernie-4.5", "ernie-4.5-thinking"],
    expectedModels: [
      "baidu/ERNIE-4.5-0.3B-PT",
      "baidu/ERNIE-4.5-0.3B-Base-PT",
      "baidu/ERNIE-4.5-21B-A3B-PT",
      "baidu/ERNIE-4.5-21B-A3B-Base-PT",
      "baidu/ERNIE-4.5-21B-A3B-Thinking",
      "baidu/ERNIE-4.5-300B-A47B-PT",
      "baidu/ERNIE-4.5-300B-A47B-Base-PT",
    ],
  },
  {
    relativePath: "packages/01-ai/src/index.ts",
    expectedFamilies: ["yi", "yi-1.5-9b-chat", "yi-coder", "yi-coder-chat"],
    expectedModels: [
      "01-ai/Yi-6B",
      "01-ai/Yi-6B-Chat",
      "01-ai/Yi-9B",
      "01-ai/Yi-34B",
      "01-ai/Yi-34B-Chat",
      "01-ai/Yi-6B-200K",
      "01-ai/Yi-9B-200K",
      "01-ai/Yi-34B-200K",
      "01-ai/Yi-1.5-6B",
      "01-ai/Yi-1.5-6B-Chat",
      "01-ai/Yi-1.5-9B",
      "01-ai/Yi-1.5-9B-Chat",
      "01-ai/Yi-1.5-9B-Chat-16K",
      "01-ai/Yi-1.5-9B-32K",
      "01-ai/Yi-1.5-34B",
      "01-ai/Yi-1.5-34B-Chat",
      "01-ai/Yi-1.5-34B-32K",
      "01-ai/Yi-1.5-34B-Chat-16K",
      "01-ai/Yi-Coder-9B",
      "01-ai/Yi-Coder-9B-Chat",
      "01-ai/Yi-Coder-1.5B",
      "01-ai/Yi-Coder-1.5B-Chat",
    ],
  },
  {
    relativePath: "packages/tiiuae/src/index.ts",
    expectedFamilies: ["falcon-rw-1b", "falcon-7b"],
    expectedModels: [
      "tiiuae/falcon-rw-1b",
      "tiiuae/falcon-rw-7b",
      "tiiuae/falcon-7b",
      "tiiuae/falcon-7b-instruct",
      "tiiuae/falcon-40b",
      "tiiuae/falcon-40b-instruct",
    ],
  },
  {
    relativePath: "packages/eleutherai/src/index.ts",
    expectedFamilies: ["gpt-neo", "polyglot-ko", "polyglot-ko-12.8", "pythia"],
    expectedModels: [
      "EleutherAI/gpt-neo-125m",
      "EleutherAI/gpt-neo-1.3B",
      "EleutherAI/gpt-neo-2.7B",
      "EleutherAI/gpt-j-6b",
      "EleutherAI/gpt-neox-20b",
      "EleutherAI/pythia-14m",
      "EleutherAI/pythia-14m-deduped",
      "EleutherAI/pythia-31m-deduped",
      "EleutherAI/pythia-70m",
      "EleutherAI/pythia-1b",
      "EleutherAI/pythia-6.9b",
      "EleutherAI/pythia-12b",
      "EleutherAI/pythia-70m-deduped",
      "EleutherAI/pythia-12b-deduped",
      "EleutherAI/polyglot-ko-1.3b",
      "EleutherAI/polyglot-ko-3.8b",
      "EleutherAI/polyglot-ko-5.8b",
      "EleutherAI/polyglot-ko-12.8b",
    ],
  },
  {
    relativePath: "packages/meituan-longcat/src/index.ts",
    expectedFamilies: ["longcat-flash-chat", "longcat-flash-lite", "longcat-flash-thinking"],
    expectedModels: [
      "meituan-longcat/LongCat-Flash-Prover",
      "meituan-longcat/LongCat-Flash-Lite",
      "meituan-longcat/LongCat-Flash-Chat",
      "meituan-longcat/LongCat-Flash-Thinking",
      "meituan-longcat/LongCat-Flash-Thinking-2601",
      "meituan-longcat/LongCat-Flash-Thinking-ZigZag",
      "meituan-longcat/LongCat-HeavyMode-Summary",
    ],
  },
  {
    relativePath: "packages/xiaomi-mimo/src/index.ts",
    expectedFamilies: ["mimo", "mimo-7b-rl-0530", "mimo-v2-flash"],
    expectedModels: [
      "XiaomiMiMo/MiMo-7B-Base",
      "XiaomiMiMo/MiMo-7B-RL",
      "XiaomiMiMo/MiMo-7B-RL-0530",
      "XiaomiMiMo/MiMo-7B-RL-Zero",
      "XiaomiMiMo/MiMo-7B-SFT",
      "XiaomiMiMo/MiMo-V2-Flash",
      "XiaomiMiMo/MiMo-V2-Flash-Base",
    ],
  },
  {
    relativePath: "packages/microsoft/src/index.ts",
    expectedFamilies: [
      "bitnet-b1.58-2b-4t",
      "nextcoder",
      "phi-1",
      "phi-3-mini",
      "phi-3-medium",
      "phi-3.5",
      "phi-4",
      "phi-4-mini",
      "phi-4-mini-flash",
      "phi-4-mini-reasoning",
      "phi-4-reasoning",
      "phi-moe",
    ],
    expectedModels: [
      "microsoft/bitnet-b1.58-2B-4T",
      "microsoft/NextCoder-7B",
      "microsoft/NextCoder-14B",
      "microsoft/NextCoder-32B",
      "microsoft/phi-1",
      "microsoft/phi-2",
      "microsoft/Phi-3-mini-4k-instruct",
      "microsoft/Phi-3-mini-128k-instruct",
      "microsoft/MediPhi",
      "microsoft/MediPhi-Instruct",
      "microsoft/Phi-3-medium-4k-instruct",
      "microsoft/Phi-3-medium-128k-instruct",
      "microsoft/Phi-3.5-mini-instruct",
      "microsoft/Phi-3.5-MoE-instruct",
      "microsoft/Phi-mini-MoE-instruct",
      "microsoft/Phi-tiny-MoE-instruct",
      "microsoft/phi-4",
      "microsoft/Phi-4-reasoning",
      "microsoft/Phi-4-reasoning-plus",
      "microsoft/Phi-4-mini-instruct",
      "microsoft/Phi-4-mini-reasoning",
      "microsoft/Phi-4-mini-flash-reasoning",
    ],
  },
  {
    relativePath: "packages/mistral/src/index.ts",
    expectedFamilies: [
      "devstral-small-2",
      "devstral-small-2505",
      "leanstral-2603",
      "mathstral-7b",
      "mamba-codestral-7b",
      "magistral-small-2507",
      "ministral-3",
      "mistral-7b-v0.1",
      "mistral-7b-v0.3",
      "mistral-nemo",
      "mistral-small-3.2",
      "mistral-small-24b",
      "mixtral-8x7b",
    ],
    expectedModels: [
      "mistralai/Devstral-Small-2-24B-Instruct-2512",
      "mistralai/Devstral-Small-2505",
      "mistralai/Devstral-Small-2507",
      "mistralai/Leanstral-2603",
      "mistralai/Magistral-Small-2506",
      "mistralai/Magistral-Small-2507",
      "mistralai/Magistral-Small-2509",
      "mistralai/Mathstral-7B-v0.1",
      "mistralai/Mamba-Codestral-7B-v0.1",
      "mistralai/Ministral-3-3B-Base-2512",
      "mistralai/Ministral-3-3B-Instruct-2512",
      "mistralai/Ministral-3-3B-Reasoning-2512",
      "mistralai/Ministral-3-8B-Base-2512",
      "mistralai/Ministral-3-8B-Instruct-2512",
      "mistralai/Ministral-3-8B-Reasoning-2512",
      "mistralai/Ministral-3-14B-Base-2512",
      "mistralai/Ministral-3-14B-Instruct-2512",
      "mistralai/Ministral-3-14B-Reasoning-2512",
      "mistralai/Mistral-7B-v0.1",
      "mistralai/Mistral-7B-Instruct-v0.1",
      "mistralai/Mistral-7B-Instruct-v0.2",
      "mistralai/Mistral-7B-v0.3",
      "mistralai/Mistral-7B-Instruct-v0.3",
      "mistralai/Mistral-Nemo-Base-2407",
      "mistralai/Mistral-Nemo-Instruct-2407",
      "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
      "mistralai/Mistral-Small-24B-Base-2501",
      "mistralai/Mistral-Small-24B-Instruct-2501",
      "mistralai/Mixtral-8x22B-v0.1",
      "mistralai/Mixtral-8x22B-Instruct-v0.1",
      "mistralai/Mixtral-8x7B-v0.1",
      "mistralai/Mixtral-8x7B-Instruct-v0.1",
    ],
  },
  {
    relativePath: "packages/huggingface-tb/src/index.ts",
    expectedFamilies: ["cosmo-1b", "smollm", "smollm-1.7b", "smollm2-16k", "smollm3", "smollm3-base"],
    expectedModels: [
      "HuggingFaceTB/cosmo-1b",
      "HuggingFaceTB/SmolLM-135M",
      "HuggingFaceTB/SmolLM-135M-Instruct",
      "HuggingFaceTB/SmolLM-360M",
      "HuggingFaceTB/SmolLM-360M-Instruct",
      "HuggingFaceTB/SmolLM-1.7B",
      "HuggingFaceTB/SmolLM-1.7B-Instruct",
      "HuggingFaceTB/SmolLM2-135M",
      "HuggingFaceTB/SmolLM2-135M-Instruct",
      "HuggingFaceTB/SmolLM2-360M",
      "HuggingFaceTB/SmolLM2-360M-Instruct",
      "HuggingFaceTB/SmolLM2-1.7B",
      "HuggingFaceTB/SmolLM2-1.7B-Instruct",
      "HuggingFaceTB/SmolLM2-1.7B-Instruct-16k",
      "HuggingFaceTB/SmolLM3-3B",
      "HuggingFaceTB/SmolLM3-3B-Base",
    ],
  },
  {
    relativePath: "packages/allenai/src/index.ts",
    expectedFamilies: [
      "olmo",
      "olmo-1",
      "olmo-0424",
      "olmo-2",
      "olmo-3-instruct",
      "olmo-hybrid",
      "olmo-hybrid-think",
      "olmoe",
      "olmoe-instruct",
      "olmoe-0125",
      "olmoe-0125-instruct",
    ],
    expectedModels: [
      "allenai/OLMo-1B",
      "allenai/OLMo-1B-hf",
      "allenai/OLMo-1B-0724-hf",
      "allenai/OLMo-7B",
      "allenai/OLMo-7B-0424",
      "allenai/OLMo-7B-Instruct",
      "allenai/OLMo-7B-hf",
      "allenai/OLMo-7B-0424-hf",
      "allenai/OLMo-7B-0724-hf",
      "allenai/OLMo-7B-0724-Instruct-hf",
      "allenai/OLMo-7B-Instruct-hf",
      "allenai/OLMo-7B-Twin-2T-hf",
      "allenai/OLMoE-1B-7B-0924",
      "allenai/OLMoE-1B-7B-0924-Instruct",
      "allenai/OLMoE-1B-7B-0125",
      "allenai/OLMoE-1B-7B-0125-Instruct",
      "allenai/OLMo-2-0425-1B",
      "allenai/OLMo-2-0425-1B-Instruct",
      "allenai/OLMo-2-0325-32B",
      "allenai/OLMo-2-1124-13B",
      "allenai/OLMo-2-1124-7B",
      "allenai/OLMo-2-1124-7B-Instruct",
      "allenai/OLMo-2-0325-32B-Instruct",
      "allenai/Olmo-3-1025-7B",
      "allenai/Olmo-3-1125-32B",
      "allenai/Olmo-3-7B-Think",
      "allenai/Olmo-3-32B-Think",
      "allenai/Olmo-3.1-32B-Think",
      "allenai/Olmo-3-7B-Instruct",
      "allenai/Olmo-3.1-32B-Instruct",
      "allenai/Olmo-Hybrid-7B",
      "allenai/Olmo-Hybrid-Instruct-SFT-7B",
      "allenai/Olmo-Hybrid-Think-SFT-7B",
    ],
  },
  {
    relativePath: "packages/ibm-granite/src/index.ts",
    expectedFamilies: [
      "granite-3-instruct",
      "granite-3.3-base",
      "granite-3.3-instruct",
      "granite-7b-base",
      "granite-7b-instruct",
      "granite-code-base",
      "granite-4",
      "granite-4-tiny-base-preview",
      "granite-4-tiny-preview",
    ],
    expectedModels: [
      "ibm-granite/granite-3.0-2b-base",
      "ibm-granite/granite-3.1-8b-base",
      "ibm-granite/granite-3.0-2b-instruct",
      "ibm-granite/granite-3.2-8b-instruct",
      "ibm-granite/granite-3.3-8b-base",
      "ibm-granite/granite-3.3-8b-instruct",
      "ibm-granite/granite-7b-base",
      "ibm-granite/granite-7b-instruct",
      "ibm-granite/granite-3b-code-base-2k",
      "ibm-granite/granite-4.0-350m-base",
      "ibm-granite/granite-4.0-h-1b",
      "ibm-granite/granite-4.0-tiny-base-preview",
      "ibm-granite/granite-4.0-tiny-preview",
    ],
  },
  {
    relativePath: "packages/ibm-research/src/index.ts",
    expectedFamilies: ["molm", "powerlm"],
    expectedModels: [
      "ibm-research/MoLM-350M-4B",
      "ibm-research/MoLM-700M-4B",
      "ibm-research/MoLM-700M-8B",
      "ibm-research/PowerLM-3b",
      "ibm-research/PowerMoE-3b",
    ],
  },
  {
    relativePath: "packages/h2oai/src/index.ts",
    expectedFamilies: [
      "danube",
      "danube2",
      "danube3-500m-chat",
      "danube3-4b-chat",
      "danube3.1-4b-chat",
    ],
    expectedModels: [
      "h2oai/h2o-danube-1.8b-base",
      "h2oai/h2o-danube-1.8b-chat",
      "h2oai/h2o-danube2-1.8b-base",
      "h2oai/h2o-danube2-1.8b-chat",
      "h2oai/h2o-danube3-500m-base",
      "h2oai/h2o-danube3-500m-chat",
      "h2oai/h2o-danube3-4b-base",
      "h2oai/h2o-danube3-4b-chat",
      "h2oai/h2o-danube3.1-4b-chat",
    ],
  },
  {
    relativePath: "packages/nanbeige/src/index.ts",
    expectedFamilies: ["nanbeige4", "nanbeige4-base"],
    expectedModels: [
      "Nanbeige/Nanbeige4-3B-Base",
      "Nanbeige/Nanbeige4.1-3B",
      "Nanbeige/Nanbeige4-3B-Thinking-2510",
      "Nanbeige/Nanbeige4-3B-Thinking-2511",
      "Nanbeige/ToolMind-Web-3B",
    ],
  },
  {
    relativePath: "packages/skt/src/index.ts",
    expectedFamilies: ["ax-3.1", "ax-light", "ax-k1"],
    expectedModels: [
      "skt/A.X-3.1",
      "skt/A.X-3.1-Light",
      "skt/A.X-4.0-Light",
      "skt/A.X-K1",
    ],
  },
  {
    relativePath: "packages/distilbert/src/index.ts",
    expectedFamilies: ["distilgpt2"],
    expectedModels: ["distilbert/distilgpt2"],
  },
  {
    relativePath: "packages/internlm/src/index.ts",
    expectedFamilies: ["internlm2.5-1.8b", "internlm2.5-20b", "internlm3", "danube"],
    expectedModels: [
      "internlm/internlm2_5-1_8b",
      "internlm/internlm2_5-20b",
      "internlm/internlm3-8b-instruct",
      "internlm/AlchemistCoder-L-7B",
    ],
  },
  {
    relativePath: "packages/baichuan-inc/src/index.ts",
    expectedFamilies: ["qwen3"],
    expectedModels: [
      "Qwen/Qwen3-0.6B",
      "Qwen/Qwen3-1.7B",
      "Qwen/Qwen3-4B",
      "Qwen/Qwen3-8B",
      "Qwen/Qwen3-14B",
      "Qwen/Qwen3-30B-A3B",
      "Qwen/Qwen3-32B",
      "Qwen/Qwen3-235B-A22B",
      "Qwen/Qwen3-4B-Instruct-2507",
      "Qwen/Qwen3-30B-A3B-Instruct-2507",
      "Qwen/Qwen3-235B-A22B-Instruct-2507",
      "Qwen/Qwen3-4B-Thinking-2507",
      "Qwen/Qwen3-Next-80B-A3B-Instruct",
      "Qwen/Qwen3-Next-80B-A3B-Thinking",
      "baichuan-inc/Baichuan-M2-32B",
      "baichuan-inc/Baichuan-M3-235B",
    ],
  },
  {
    relativePath: "packages/ai-sage/src/index.ts",
    expectedFamilies: ["gigachat-20b-base", "gigachat-20b-instruct", "gigachat3", "gigachat3.1"],
    expectedModels: [
      "ai-sage/GigaChat-20B-A3B-base",
      "ai-sage/GigaChat-20B-A3B-instruct",
      "ai-sage/GigaChat-20B-A3B-instruct-v1.5",
      "ai-sage/GigaChat3-10B-A1.8B-base",
      "ai-sage/GigaChat3-10B-A1.8B",
      "ai-sage/GigaChat3-702B-A36B-preview",
      "ai-sage/GigaChat3.1-10B-A1.8B",
      "ai-sage/GigaChat3.1-702B-A36B",
    ],
  },
  {
    relativePath: "packages/essentialai/src/index.ts",
    expectedFamilies: ["rnj-1"],
    expectedModels: ["EssentialAI/rnj-1", "EssentialAI/rnj-1-instruct"],
  },
  {
    relativePath: "packages/servicenow-ai/src/index.ts",
    expectedFamilies: ["apriel-5b"],
    expectedModels: [
      "ServiceNow-AI/Apriel-5B-Base",
      "ServiceNow-AI/Apriel-5B-Instruct",
    ],
  },
  {
    relativePath: "packages/salesforce/src/index.ts",
    expectedFamilies: ["codegen", "codegen-nl", "codegen2"],
    expectedModels: [
      "Salesforce/codegen-350M-mono",
      "Salesforce/codegen-350M-multi",
      "Salesforce/codegen-350M-nl",
      "Salesforce/codegen-2B-mono",
      "Salesforce/codegen-2B-multi",
      "Salesforce/codegen-2B-nl",
      "Salesforce/codegen-6B-mono",
      "Salesforce/codegen-6B-multi",
      "Salesforce/codegen-6B-nl",
      "Salesforce/codegen-16B-mono",
      "Salesforce/codegen-16B-multi",
      "Salesforce/codegen-16B-nl",
      "Salesforce/codegen2-1B_P",
      "Salesforce/codegen2-3_7B_P",
      "Salesforce/codegen2-7B_P",
      "Salesforce/codegen2-16B_P",
    ],
  },
  {
    relativePath: "packages/cerebras/src/index.ts",
    expectedFamilies: ["btlm-3b-8k-chat", "cerebras-gpt"],
    expectedModels: [
      "cerebras/Cerebras-GPT-111M",
      "cerebras/Cerebras-GPT-256M",
      "cerebras/Cerebras-GPT-590M",
      "cerebras/Cerebras-GPT-1.3B",
      "cerebras/Cerebras-GPT-2.7B",
      "cerebras/Cerebras-GPT-6.7B",
      "cerebras/Cerebras-GPT-13B",
      "cerebras/btlm-3b-8k-base",
      "cerebras/btlm-3b-8k-chat",
    ],
  },
  {
    relativePath: "packages/inclusionai/src/index.ts",
    expectedFamilies: [
      "llada2",
      "ring-2.5-1t",
      "ling-2",
      "ring-mini-2.0",
      "ring-flash-2.0",
      "ring-1t",
      "qwen2.5",
      "qwen3",
    ],
    expectedModels: [
      "inclusionAI/LLaDA2.0-mini",
      "inclusionAI/LLaDA2.0-flash",
      "inclusionAI/LLaDA2.1-mini",
      "inclusionAI/LLaDA2.1-flash",
      "inclusionAI/LLaDA-MoE-7B-A1B-Base",
      "inclusionAI/Ring-2.5-1T",
      "inclusionAI/Ling-2.5-1T",
      "inclusionAI/Ling-mini-2.0",
      "inclusionAI/Ling-flash-2.0",
      "inclusionAI/Ling-1T",
      "inclusionAI/Ring-mini-2.0",
      "inclusionAI/Ling-flash-base-2.0",
      "inclusionAI/Ring-flash-2.0",
      "inclusionAI/Ring-1T",
      "inclusionAI/GroveMoE-Base",
      "inclusionAI/Qwen3-32B-AWorld",
      "inclusionAI/AReaL-SEA-235B-A22B",
      "inclusionAI/GroveMoE-Inst",
      "inclusionAI/AReaL-boba-2-14B-Open",
      "inclusionAI/AReaL-boba-2-8B-Open",
      "inclusionAI/AReaL-boba-2-32B",
      "inclusionAI/AReaL-boba-2-8B",
      "inclusionAI/AReaL-boba-2-14B",
      "Qwen/Qwen2.5-32B-Instruct",
      "Qwen/Qwen3-32B",
    ],
  },
  {
    relativePath: "packages/pleias/src/index.ts",
    expectedFamilies: [
      "pleias-350m",
      "pleias-1.2b",
      "pleias-3b",
      "pleias-pico",
      "baguettotron",
      "monad",
    ],
    expectedModels: [
      "PleIAs/Pleias-350m-Preview",
      "PleIAs/Pleias-1.2b-Preview",
      "PleIAs/Pleias-3b-Preview",
      "PleIAs/Pleias-Pico",
      "PleIAs/Baguettotron",
      "PleIAs/Monad",
    ],
  },
  {
    relativePath: "packages/janhq/src/index.ts",
    expectedFamilies: ["qwen3"],
    expectedModels: [
      "Qwen/Qwen3-0.6B",
      "Qwen/Qwen3-1.7B",
      "Qwen/Qwen3-4B",
      "Qwen/Qwen3-8B",
      "Qwen/Qwen3-14B",
      "Qwen/Qwen3-30B-A3B",
      "Qwen/Qwen3-32B",
      "Qwen/Qwen3-235B-A22B",
      "Qwen/Qwen3-4B-Instruct-2507",
      "Qwen/Qwen3-30B-A3B-Instruct-2507",
      "Qwen/Qwen3-235B-A22B-Instruct-2507",
      "Qwen/Qwen3-4B-Thinking-2507",
      "Qwen/Qwen3-Next-80B-A3B-Instruct",
      "Qwen/Qwen3-Next-80B-A3B-Thinking",
      "janhq/Jan-v1-4B",
      "janhq/Jan-v1-edge",
      "janhq/Jan-v1-2509",
      "janhq/Jan-v3-4B-base-instruct",
      "janhq/Jan-v3.5-4B",
      "janhq/Jan-code-4b",
    ],
  },
  {
    relativePath: "packages/abeja/src/index.ts",
    expectedFamilies: ["qwen2.5", "qwen3"],
    expectedModels: [
      "Qwen/Qwen2.5-32B-Instruct",
      "Qwen/Qwen3-14B",
      "abeja/ABEJA-Qwen2.5-32b-Japanese-v1.0",
      "abeja/ABEJA-Qwen2.5-7b-Japanese-v0.1",
      "abeja/ABEJA-QwQ32b-Reasoning-Japanese-v1.0",
      "abeja/ABEJA-Qwen3-14B-Agentic-256k-v0.1",
    ],
  },
  {
    relativePath: "packages/zyphra/src/index.ts",
    expectedFamilies: [
      "zamba-7b-v1",
      "zamba2-1.2b",
      "zamba2-2.7b",
      "zamba2-instruct",
      "zamba2-instruct-v2",
      "zr1-1.5b",
      "zaya1",
    ],
    expectedModels: [
      "Zyphra/Zamba-7B-v1",
      "Zyphra/Zamba2-1.2B",
      "Zyphra/Zamba2-1.2B-instruct",
      "Zyphra/Zamba2-2.7B",
      "Zyphra/Zamba2-2.7B-instruct",
      "Zyphra/Zamba2-7B-Instruct",
      "Zyphra/Zamba2-1.2B-Instruct-v2",
      "Zyphra/Zamba2-2.7B-Instruct-v2",
      "Zyphra/Zamba2-7B-Instruct-v2",
      "Zyphra/ZR1-1.5B",
      "Zyphra/ZAYA1-base",
      "Zyphra/ZAYA1-reasoning-base",
    ],
  },
  {
    relativePath: "packages/arcee-ai/src/index.ts",
    expectedFamilies: [
      "trinity-large-truebase",
      "trinity-large",
      "trinity-large-thinking",
    ],
    expectedModels: [
      "arcee-ai/Trinity-Large-TrueBase",
      "arcee-ai/Trinity-Large-Base",
      "arcee-ai/Trinity-Large-Preview",
      "arcee-ai/Trinity-Large-Thinking",
    ],
  },
  {
    relativePath: "packages/state-spaces/src/index.ts",
    expectedFamilies: ["mamba-130m", "mamba-790m"],
    expectedModels: [
      "state-spaces/mamba-130m-hf",
      "state-spaces/mamba-370m-hf",
      "state-spaces/mamba-790m-hf",
      "state-spaces/mamba-1.4b-hf",
      "state-spaces/mamba-2.8b-hf",
    ],
  },
  {
    relativePath: "packages/snowflake/src/index.ts",
    expectedFamilies: ["snowflake-arctic-base", "snowflake-arctic-instruct"],
    expectedModels: [
      "Snowflake/snowflake-arctic-base",
      "Snowflake/snowflake-arctic-instruct",
    ],
  },
  {
    relativePath: "packages/cyberagent/src/index.ts",
    expectedFamilies: ["open-calm", "calm2", "calm3"],
    expectedModels: [
      "cyberagent/open-calm-1b",
      "cyberagent/open-calm-small",
      "cyberagent/open-calm-medium",
      "cyberagent/open-calm-3b",
      "cyberagent/open-calm-large",
      "cyberagent/open-calm-7b",
      "cyberagent/calm2-7b",
      "cyberagent/calm2-7b-chat",
      "cyberagent/calm3-22b-chat",
    ],
  },
  {
    relativePath: "packages/swiss-ai/src/index.ts",
    expectedFamilies: ["apertus", "apertus-instruct"],
    expectedModels: [
      "swiss-ai/Apertus-8B-2509",
      "swiss-ai/Apertus-70B-2509",
      "swiss-ai/Apertus-8B-Instruct-2509",
      "swiss-ai/Apertus-70B-Instruct-2509",
    ],
  },
  {
    relativePath: "packages/tinyllama/src/index.ts",
    expectedFamilies: ["danube"],
    expectedModels: [
      "h2oai/h2o-danube-1.8b-base",
      "h2oai/h2o-danube-1.8b-chat",
      "TinyLlama/TinyLlama_v1.1",
      "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    ],
  },
  {
    relativePath: "packages/upstage/src/index.ts",
    expectedFamilies: ["solar", "solar-pro"],
    expectedModels: [
      "upstage/SOLAR-10.7B-v1.0",
      "upstage/TinySolar-248m-4k",
      "upstage/solar-pro-preview-instruct",
    ],
  },
  {
    relativePath: "packages/openai/src/index.ts",
    expectedFamilies: ["gpt-oss"],
    expectedModels: ["openai/gpt-oss-20b", "openai/gpt-oss-120b"],
  },
  {
    relativePath: "packages/gsai-ml/src/index.ts",
    expectedFamilies: ["llada", "llada-base", "refusion"],
    expectedModels: [
      "GSAI-ML/LLaDA-8B-Instruct",
      "GSAI-ML/LLaDA-1.5",
      "GSAI-ML/LLaDA-8B-Base",
      "GSAI-ML/ReFusion",
    ],
  },
  {
    relativePath: "packages/bytedance-seed/src/index.ts",
    expectedFamilies: ["academic-ds", "seed-oss", "seed-coder", "stable-diffcoder"],
    expectedModels: [
      "ByteDance-Seed/academic-ds-9B",
      "ByteDance-Seed/Seed-OSS-36B-Base",
      "ByteDance-Seed/Seed-OSS-36B-Instruct",
      "ByteDance-Seed/Seed-OSS-36B-Base-woSyn",
      "ByteDance-Seed/Seed-Coder-8B-Base",
      "ByteDance-Seed/Seed-Coder-8B-Instruct",
      "ByteDance-Seed/Seed-Coder-8B-Reasoning",
      "ByteDance-Seed/Stable-DiffCoder-8B-Base",
      "ByteDance-Seed/Stable-DiffCoder-8B-Instruct",
    ],
  },
  {
    relativePath: "packages/openbmb/src/index.ts",
    expectedFamilies: [
      "agentcpm-explore",
      "minicpm-s-1b",
      "minicpm-sala",
      "minicpm3",
      "minicpm4",
      "minicpm-moe",
    ],
    expectedModels: [
      "openbmb/AgentCPM-Explore",
      "openbmb/AgentCPM-Report",
      "openbmb/MiniCPM-S-1B-sft",
      "openbmb/MiniCPM-SALA",
      "openbmb/MiniCPM3-4B",
      "openbmb/MiniCPM4-0.5B",
      "openbmb/MiniCPM4-8B",
      "openbmb/MiniCPM4.1-8B",
      "openbmb/BitCPM4-0.5B",
      "openbmb/BitCPM4-1B",
      "openbmb/MiniCPM4-MCP",
      "openbmb/MiniCPM4-Survey",
      "openbmb/NOSA-1B",
      "openbmb/NOSA-3B",
      "openbmb/NOSA-8B",
      "openbmb/MiniCPM-MoE-8x2B",
    ],
  },
] as const

/** 全家桶包当前应聚合的 family。 */
const EXPECTED_ALL_FAMILIES = [
  "jamba-v0.1",
  "jamba2",
  "crystal",
  "k2",
  "k2-chat",
  "k2-think-v2",
  "sarvam-30b",
  "sarvam-m",
  "yi",
  "yi-1.5-9b-chat",
  "yi-coder",
  "yi-coder-chat",
  "dream-v0",
  "dreamon-v0",
  "eurollm-1.7b",
  "eurollm-1.7b-instruct",
  "eurollm-2512",
  "eurollm-2512-instruct",
  "devstral-small-2",
  "devstral-small-2505",
  "deepseek-r1",
  "deepseek-v3",
  "deepseek-v3.1",
  "deepseek-v3.2",
  "distilgpt2",
  "falcon-rw-1b",
  "falcon-7b",
  "gigachat-20b-base",
  "gigachat-20b-instruct",
  "gigachat3",
  "gigachat3.1",
  "rnj-1",
  "apriel-5b",
  "codegen",
  "codegen-nl",
  "codegen2",
  "cerebras-gpt",
  "btlm-3b-8k-chat",
  "llada2",
  "ring-2.5-1t",
  "ling-2",
  "ring-mini-2.0",
  "ring-flash-2.0",
  "ring-1t",
  "pleias-350m",
  "pleias-1.2b",
  "pleias-3b",
  "pleias-pico",
  "baguettotron",
  "monad",
  "zamba-7b-v1",
  "zamba2-1.2b",
  "zamba2-2.7b",
  "zamba2-instruct",
  "zamba2-instruct-v2",
  "zr1-1.5b",
  "zaya1",
  "trinity-large-truebase",
  "trinity-large",
  "trinity-large-thinking",
  "internlm2.5-1.8b",
  "internlm2.5-20b",
  "internlm3",
  "bitnet-b1.58-2b-4t",
  "pagnol",
  "pagnol-xl",
  "alfred-40b-1023",
  "gpt-neo",
  "cosmo-1b",
  "danube",
  "danube2",
  "danube3-500m-chat",
  "danube3-4b-chat",
  "danube3.1-4b-chat",
  "nanbeige4",
  "nanbeige4-base",
  "ax-3.1",
  "ax-light",
  "ax-k1",
  "solar",
  "solar-pro",
  "gpt-oss",
  "llada",
  "llada-base",
  "refusion",
  "glm-4.7",
  "glm-5",
  "granite-3-instruct",
  "granite-3.3-base",
  "granite-3.3-instruct",
  "granite-7b-base",
  "granite-7b-instruct",
  "granite-code-base",
  "granite-4",
  "granite-4-tiny-base-preview",
  "granite-4-tiny-preview",
  "leanstral-2603",
  "molm",
  "powerlm",
  "mamba-130m",
  "mamba-790m",
  "snowflake-arctic-base",
  "snowflake-arctic-instruct",
  "apertus",
  "apertus-instruct",
  "longcat-flash-chat",
  "longcat-flash-lite",
  "longcat-flash-thinking",
  "academic-ds",
  "agentcpm-explore",
  "minicpm-s-1b",
  "minicpm-sala",
  "minicpm3",
  "minicpm4",
  "minicpm-moe",
  "mimo",
  "mimo-7b-rl-0530",
  "mimo-v2-flash",
  "decicoder-1b",
  "salamandra",
  "salamandra-instruct",
  "marco-o1",
  "dj-refine-1b",
  "ernie-4.5",
  "ernie-4.5-thinking",
  "mathstral-7b",
  "mamba-codestral-7b",
  "magistral-small-2507",
  "ministral-3",
  "mistral-7b-v0.1",
  "mistral-7b-v0.3",
  "mistral-nemo",
  "mistral-small-3.2",
  "mistral-small-24b",
  "mixtral-8x7b",
  "nextcoder",
  "seed-coder",
  "seed-oss",
  "smollm",
  "smollm-1.7b",
  "smollm2-16k",
  "smollm3",
  "smollm3-base",
  "stable-diffcoder",
  "olmo",
  "olmo-1",
  "olmo-0424",
  "olmo-2",
  "olmo-3-instruct",
  "olmo-hybrid",
  "olmo-hybrid-think",
  "olmoe",
  "olmoe-instruct",
  "olmoe-0125",
  "olmoe-0125-instruct",
  "phi-1",
  "phi-3-mini",
  "phi-3-medium",
  "phi-3.5",
  "phi-4",
  "phi-4-mini",
  "phi-4-mini-flash",
  "phi-4-mini-reasoning",
  "phi-4-reasoning",
  "phi-moe",
  "polyglot-ko",
  "polyglot-ko-12.8",
  "pythia",
  "qwen2",
  "qwen2.5",
  "qwen3",
  "qwen3-coder-next",
  "qwen3.5",
  "qwen3.5-base",
  "step-3.5-flash",
] as const

/**
 * 动态导入本地 TypeScript 模块。
 * 输入：相对仓库根目录的模块路径。
 * 输出：对应模块的导出对象。
 */
async function importModule(relativePath: string) {
  const fullPath = resolve(REPO_ROOT, relativePath)
  expect(existsSync(fullPath)).toBe(true)
  return import(pathToFileURL(fullPath).href)
}

describe("family packages", () => {
  it.each(VENDOR_PACKAGE_CASES)(
    "$relativePath 只注册自己的厂商 family",
    async ({ relativePath, expectedFamilies, expectedModels }) => {
      const core = await importModule("packages/core/src/index.ts")
      const vendorPackage = await importModule(relativePath)

      core.resetRegistry()
      vendorPackage.registerBuiltins()

      expect(core.listSupportedFamilies().sort()).toEqual([...expectedFamilies].sort())
      expect(core.listSupportedModels()).toEqual(expect.arrayContaining([...expectedModels]))
    }
  )

  it("qwen 包只注册 qwen 系列 family", async () => {
    const core = await importModule("packages/core/src/index.ts")
    const qwen = await importModule("packages/qwen/src/index.ts")

    core.resetRegistry()
    qwen.registerBuiltins()

    expect(core.listSupportedFamilies().sort()).toEqual(
      ["qwen2", "qwen2.5", "qwen3", "qwen3.5", "qwen3.5-base", "qwen3-coder-next"].sort()
    )
    expect(core.listSupportedModels()).toEqual(
      expect.arrayContaining([
        "Qwen/Qwen2-7B-Instruct",
        "Qwen/Qwen2.5-7B-Instruct",
        "Qwen/Qwen3-14B-Base",
        "Qwen/Qwen3-0.6B",
        "Qwen/Qwen3-Next-80B-A3B-Thinking",
        "Qwen/Qwen3-235B-A22B-Instruct-2507",
        "Qwen/Qwen3-235B-A22B-Thinking-2507",
        "Qwen/Qwen3.5-0.8B",
        "Qwen/Qwen3.5-27B",
        "Qwen/Qwen3.5-0.8B-Base",
        "Qwen/Qwen3.5-397B-A17B",
        "Qwen/Qwen3-Coder-Next",
        "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        "Qwen/Qwen3-Coder-Next-Base",
        "Qwen/QwQ-32B",
      ])
    )
  })

  it("deepseek 包只注册 deepseek 系列 family", async () => {
    const core = await importModule("packages/core/src/index.ts")
    const deepseek = await importModule("packages/deepseek/src/index.ts")

    core.resetRegistry()
    deepseek.registerBuiltins()

    expect(core.listSupportedFamilies().sort()).toEqual(
      ["deepseek-v3", "deepseek-r1", "deepseek-v3.1", "deepseek-v3.2"].sort()
    )
    expect(core.listSupportedModels()).toEqual(
      expect.arrayContaining([
        "deepseek-ai/DeepSeek-V3",
        "deepseek-ai/DeepSeek-V3-0324",
        "deepseek-ai/DeepSeek-R1",
        "deepseek-ai/DeepSeek-R1-0528",
        "deepseek-ai/DeepSeek-V3.1",
        "deepseek-ai/DeepSeek-V3.2-Exp",
        "deepseek-ai/DeepSeek-V3.2",
      ])
    )
  })

  it("step 包只注册 step 系列 family", async () => {
    const core = await importModule("packages/core/src/index.ts")
    const step = await importModule("packages/step/src/index.ts")

    core.resetRegistry()
    step.registerBuiltins()

    expect(core.listSupportedFamilies().sort()).toEqual(["step-3.5-flash"].sort())
    expect(core.listSupportedModels()).toEqual(
      expect.arrayContaining([
        "stepfun-ai/Step-3.5-Flash",
        "stepfun-ai/Step-3.5-Flash-Base-Midtrain",
      ])
    )
  })

  it("glm 包只注册 glm 系列 family", async () => {
    const core = await importModule("packages/core/src/index.ts")
    const glm = await importModule("packages/glm/src/index.ts")

    core.resetRegistry()
    glm.registerBuiltins()

    expect(core.listSupportedFamilies().sort()).toEqual(["glm-4.7", "glm-5"].sort())
    expect(core.listSupportedModels()).toEqual(
      expect.arrayContaining([
        "zai-org/GLM-4.5",
        "zai-org/GLM-4.5-Base",
        "zai-org/GLM-4.5-Air",
        "zai-org/GLM-4.5-Air-Base",
        "zai-org/GLM-4.6",
        "zai-org/GLM-4.7",
        "zai-org/GLM-4.7-Flash",
        "zai-org/GLM-5",
      ])
    )
  })

  it("全家桶包注册全部内置 family", async () => {
    const all = await importModule("packages/all/src/index.ts")

    all.resetRegistry()
    all.registerBuiltins()

    expect(all.listSupportedFamilies().sort()).toEqual([...EXPECTED_ALL_FAMILIES].sort())
  })
})
